app/components/Head.js
app/pages/Layout.js
app/pages/Logs.js
app/plugins/swarfarm-logger.js
css/style.css

Fixed side menu to screen, compacted log format a little bit

Layout improvements - 

---

app/proxy/SWProxy.js

Only log that the server is started if the server really is listening

Handled EADDRINUSE error

---

app/plugins/live-sync.js

Added craft and reappraisal to live-sync

Added live-sync plugin

---

app/main.js
app/pages/Logs.js
app/pages/Settings.js
app/plugins/full-logger.js
app/proxy/SWProxy.js
package.json

Better performance in Log section
New option: Clear Log on every login Resolves #11
New option: Delete log file before quitting app (FullLogger) Resolves #38

New options / Improvements

---

app/mapping.js
app/plugins/run-logger.js

Added support for grindstones / enchanted gems to runlogger

---

app/plugins/rune-drop-efficiency.js

Now elemental dungeons log rune efficiency!

Added rune efficiency for rift dungeon

---

app/plugins/run-logger.js

Fixed mana drops in raids

---

app/View.js
app/components/SettingsPlugin.js
app/pages/Logs.js
app/pages/Settings.js
app/plugins/rune-drop-efficiency.js

And fixed up eslint errors. In testing settings I found that the `self = this;` was unnecessary but double check me on that please.

Fixed an error when receiving an F in rift raids

---

app/main.js
app/plugins/version-checker.js
package-lock.json

I wasn't able to find a better way to get the current app version during plugin loading other than adding it to the global object in main.js.  Let me know if there is a different way that you would like this handled and I'm happy to make any changes!
This is for issues #46

Version checker plugin

---

app/plugins/swarfarm-logger.js

Should resolve #189 
Reading this file though shows multiple methods of checking for an error. It may be good to standardize them to make the code cleaner and easier to maintain.

Added check for error when uploading profile

---

README.md

Adding a step to "cd" to the right directory before moving on to the rest of the dev setup process.

Changing README.md to modify Dev envrionment setup process.

---

app/components/SettingsItem.js
app/components/SettingsPlugin.js
app/main.js
app/plugins/swarfarm-logger.js
package-lock.json
package.json

Updated swarfarm-logger to use API endpoints. Support for multiple game accounts to API key mapping. Added auto accepted commands refresh on hourly basis or if server says to do so.

Multiple swarfarm-logger updates

---

.gitignore
app/components/Head.js
app/main.js
app/proxy/SWProxy.js
css/style.css
package-lock.json
package.json

Converting branch to PR to make discussion easier.

Proof of concept HTTPS intercept

---

.gitignore
package.json

Reverting back https changes for now

---

app/plugins/swarfarm-logger.js

Settings changes do not require SWEX restart, more robust error handling, informational messages regarding API key, and automatic API key sanitization.

swarfarm-logger behavior improvements

---

.eslintrc
app/plugins/live-sync.js
app/plugins/run-logger.js
app/plugins/rune-drop-efficiency.js
package-lock.json
package.json

Migrate plugins to BattleDungeonResult_V2

---

app/main.js
app/pages/Settings.js
package-lock.json
package.json

- Related to https://github.com/Xzandro/sw-exporter/issues/343

Minimize to system tray

---

app/pages/Logs.js
css/style.css

Updates Logs page to look slightly better and fully utilize semantic-ui's `<Label>` features.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>

Logs UI Improvement

---

app/mapping.js
app/proxy/SWProxy.js
package-lock.json
package.json

-Updated mappings
-Added a better way to append server data to JSON commands
-Added SWEX version to JSON commands

Release 0.0.50

---

app/components/Head.js
app/main.js
app/proxy/SWProxy.js

I'm not sure whether the button should be visible in non-steam mode or not

Add "Get & Install Cert" button (steam only) 
